# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bfa099a983a20d5468356287c5728a65"
name = "c-to-s"
handle = "c-to-s"
application_url = "https://msie-disclaimer-webcast-bbs.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "gen-test-store-individual.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://example.com/api/auth",
  "https://msie-disclaimer-webcast-bbs.trycloudflare.com/auth/callback",
  "https://msie-disclaimer-webcast-bbs.trycloudflare.com/auth/shopify/callback",
  "https://msie-disclaimer-webcast-bbs.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
